name = "PackageNursery"
uuid = "efe96826-6319-11ea-2526-2d08b851a775"
repo = "https://github.com/j-fu/PackageNursery.jl.git"
description = "Registry for packages under development"

[packages]
0714413a-66da-11ea-1294-e93a8f6a993b = { name = "NurseryTest", path = "N/NurseryTest" }
1015158d-cf91-42d0-8ede-00fb4817e22a = { name = "XGrid", path = "X/XGrid" }
10287013-a584-5a38-a29a-42553acd0316 = { name = "vtkfig_jll", path = "V/vtkfig_jll" }
19f70b67-2887-4cf9-b19e-fe1a30c34d85 = { name = "PlutoVTKPlot", path = "P/PlutoVTKPlot" }
529833da-d7f1-5821-aee9-3785d4589272 = { name = "VTKMinimal_jll", path = "V/VTKMinimal_jll" }
57876ffe-7b7d-4c51-befe-9eb7dc4baaca = { name = "PlutoCanvasPlot", path = "P/PlutoCanvasPlot" }
63b67fce-66f7-11ea-1808-1361d8c55bf4 = { name = "VTKView", path = "V/VTKView" }
a3567244-722b-4f42-a7ec-0aeabca28c09 = { name = "RotatingElectrodes", path = "R/RotatingElectrodes" }
fdf3a005-71a1-4f4b-b6cc-89be6b2f2afa = { name = "TwoPointDirichletFlux", path = "T/TwoPointDirichletFlux" }
